# Generated by Django 3.2 on 2022-03-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_group', related_query_name='owned_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='join_requests', related_query_name='join_requests', to='network.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='join_requests', related_query_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('accepted', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_requests', related_query_name='received_requests', to='network.group')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_requests', related_query_name='sent_requests', to='network.group')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', related_query_name='users', to='network.group'),
        ),
    ]
